### ISSUE TITLE
Google Earth Autoplay Tours don't always begin after SpaceNav navigation

### ISSUE THREAD

**Issue by axisofentropy** [EndPointCorp/lg_ros_nodes#102]
1. Fly around Earth with the SpaceNav.
2. Select a different Presentation, which publishes the hidden "Introduction" scene with an autoplay Earth Tour asset.
3. The Earth Tour will not autoplay.

However:
* Other scenes with Earth Tours do autoplay.
* The intro scenes do autoplay if the SpaceNav wasn't previously touched.

**Comment by axisofentropy** [comment]
First thing I'd look at: what's different about the Introduction Scenes' KML files?

**Comment by wzin** [comment]
This couldnt be reproduced as far as I know. Closing.
