### ISSUE TITLE
Street View not tilting upon SpaceNav input

### ISSUE THREAD

**Issue by axisofentropy** [EndPointCorp/lg_ros_nodes#103]
<content removed>

**Comment by axisofentropy** [comment]
Wojtek says:

> There's tilt ROS node parameter named "tilt" - see the docs for lg_sv. It somewhat degrades performance which is poor but acceptable without it. I would keep it enabled (by default it's disabled.)

**Comment by wzin** [comment]
lg_sv_nonfree works fine
