### ISSUE TITLE
Set title for lg_sv pano.html and index.html

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#115]
pano.html and index.html should have a `<title>` because those pages are loaded on systems that monitor titles of pages that are loaded on browsers

child of https://github.com/EndPointCorp/portal-ocean/issues/40

**Comment by minshallj** [comment]
What was the title supposed to be again? Hmm, I'll just go with `panoviewer` for both. Change it if it's wrong please!

**Comment by wzin** [comment]
This is for portal to be able to monitor the title of the page.

**Comment by wzin** [comment]
Set in 1.1.23 - closing.
