### ISSUE TITLE
Consider building our own rosbridge

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#117]
`/opt/ros/indigo/lib/python2.7/dist-packages/rosbridge_library/internal/publishers.py`

comment out:

```
#if not self._publishers[topic].has_clients():
#    self._publishers[topic].unregister()
#    del self._publishers[topic]
```

otherwise there will be a problem with unregistering/registering of publishers thru rosbridge

**Comment by mvollrath** [comment]
We have a [patch in lg-live-image](https://github.com/EndPointCorp/lg-live-image/blob/portal/config/includes.chroot/patches/opt/ros/indigo/lib/python2.7/dist-packages/rosbridge_library/internal/publishers.py.lg_patch) for this particular issue, but that doesn't help us in docker environments.  We might benefit a little bit by accelerating distribution of upstream releases, it is usually over a month before a rosbridge release hits their apt servers.
