### ISSUE TITLE
Make support for setting user agent in ManagedBrowser

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#125]
Child of https://github.com/EndPointCorp/lg_chef/issues/463

Requirements:
- make it possible to set user agent via "metadata" attribute in [interactivespaces_msgs.GenericMessage](https://github.com/EndPointCorp/lg_ros_nodes/blob/development/interactivespaces_msgs/README.md)
- use following proposed data structure in the message:

```json
{
"activity_config": {
 "google-chrome": {
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36" 
  } 
 }
}
```

Dev notes:
- ManagedBrowser: https://github.com/EndPointCorp/lg_ros_nodes/blob/development/lg_common/src/lg_common/managed_browser.py#L27

**Comment by mvollrath** [comment]
kwargs are already consumed by ManagedBrowser, so if you instantiate like:

```python
browser = ManagedBrowser(..., user_agent="foo", ...)
```

It will translate this to `--user-agent=foo` on the command line.

I don't know if this is helpful for pulling in a user agent from that metadata, but seems like it could be.
