### ISSUE TITLE
Implement configurable automatic relaunch of processes

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#132]
Some processes just continue eating up memory e.g. Google Earth.

It would be nice to have a configurable way of relaunching processes on the basis of calculation of soft limits and hard limits:
- SOFT limit:
  - try to wait for application to either: enter `HIDDEN` mode or wait for `/activity/active` to turn to "False" or `/operation_mode/mode` = `standby` (the other mode would be `operating`)
- HARD limit:
  - respawn the process despite any conditions that are mentioned above

a limit may consist of:
- cpu usage:
  - `/limits/cpu/hard` = 99
  - `/limits/cpu/soft` = 100
- memory usage
  - `/limits/memory/hard` = 1024M
  - `/limits/memory/soft` = 1128M
- diskspace usage ( guard on a specific configurable directory or set of dirs )
  - `/limits/disk_space/earth` = "/home/lg/something:1024:1128"
  - `/limits/disk_space/adhoc` = s.a.a.
  - `/limits/disk_space/streetview` = s.a.a.
  - `/limits/disk_space/generic` = s.a.a

**Comment by wzin** [comment]
Please attach PR to this issue.

**Comment by axisofentropy** [comment]
Would this be handled by the ROS node spawning said process?

**Comment by wzin** [comment]
I think we can abandon this idea. Nodes should handle their resources by themselves.
