### ISSUE TITLE
Lower the amount of kmlsync logs

### ISSUE THREAD

**Issue by minshallj** [EndPointCorp/lg_ros_nodes#137]
Maybe there should be a debug mode that could allow the debugging, but other than that there's no need to print out every time we get a request on the server. The logs are getting large.

**Comment by wzin** [comment]
+1 - moved to ready for backlog. This should be moved to ready for development soon.

**Comment by wzin** [comment]
Fixed - all loginfos were kinda irrelevant and low-priority. I moved them to logdebug and one got moved to logerr.

**Comment by minshallj** [comment]
Did that reduce the size of the logs? Or just re-classify them?

**Comment by wzin** [comment]
@minshallj it reduces amount of rosout logs whcih are producing uncompressable 100-200MB per day in our case because default verbosity for rosout_agg topic which is causing the problem is LOG. Once you switch to DEBUG wil get tons of logdebug messages that you (probably) want.
