### ISSUE TITLE
Prevent duplicate KML loading in Earth

### ISSUE THREAD

**Issue by axisofentropy** [EndPointCorp/lg_ros_nodes#140]
We saw this on the two staging systems, `testtn` and `devtn`.  The Queens KML GroundOverlay persisted only on the `center` display even after unloading the Scene.
![queens_overlay](https://cloud.githubusercontent.com/assets/66315/12237688/8c4f80fa-b845-11e5-92ae-89aa547ff9bc.png)
This is probably because the ROS node was telling it to load this asset twice, but only unloading once.

					<NetworkLink id="http___lg_head_8088_roscoe_assets_asset_storage_barclays_ada_queens_tour_kml">
						<name>http___lg_head_8088_roscoe_assets_asset_storage_barclays_ada_queens_tour_kml</name>
						<Link>
							<href>http://lg-head:8088/roscoe_assets/asset_storage/barclays_ada-queens-tour.kml</href>
						</Link>
					</NetworkLink>
					<NetworkLink id="http___lg_head_8088_roscoe_assets_asset_storage_barclays_ada_queens_tour_kml">
						<name>http___lg_head_8088_roscoe_assets_asset_storage_barclays_ada_queens_tour_kml</name>
						<Link>
							<href>http://lg-head:8088/roscoe_assets/asset_storage/barclays_ada-queens-tour.kml</href>
						</Link>
					</NetworkLink>

This is probably a bug within Earth, but that's not going to be fixed, so our ROS node should prevent duplicate asset names from being loaded.

**Comment by mvollrath** [comment]
I wouldn't assume that this is an Earth bug.  kmlsync is pretty hairy.  We should write an automated test that hits kmlsync with about 100 add and then 100 remove requests simultaneously and go from there.

**Comment by mvollrath** [comment]
Also seen: KML not loaded where it should be.

**Comment by wzin** [comment]
This got fixed.
