### ISSUE TITLE
Fix panoviewer memory consumption

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#146]
https://www.flowdock.com/app/endpoint/support/threads/NtkS_iCGhaIkvdyLtfKBxQK0SKX

Panoviewer consumes a lot of memory after some time. It leads to tab crashes and swapping (3.5VIRT / 2.5RES for one tab).

Consider following:
- identify the leak or run js garbage collecting frequently
- unload assets as soon as pv stops being used
- kill browsers if not used for a long time (e.g. in the background) ( #132  may be related )

**Comment by minshallj** [comment]
Tested fix in #147 w/ @mababio, and it seemed to work, closing
