### ISSUE TITLE
Specify language in GE labels

### ISSUE THREAD

**Issue by mikemerrill** [EndPointCorp/lg_ros_nodes#150]
There is a need to be able to specify the language showing on the labels in GE. Currently the default seems to be English, with no mechanism for changing to anything else.

**Comment by wzin** [comment]
This may be already working fine with `DHCP_LANG` persona var in `lg-live-image` which is [here]. This persona var setting may have to be ported to `roscoe` branch.

Another option would be a possibility to dynamically specify environment variables (like `LG_LANG`) for processes to be able to set language of labels.

For now - let's port the language setting from [lg-live-image](https://github.com/EndPointCorp/lg-live-image/blob/azero-raring-earth32/config/includes.chroot/home/lg/etc/shell.conf#L19) back to `roscoe` branch.

**Comment by FuriousJulius** [comment]
I've added support for DHCP_LANG for the roscoe branch in the roslaunch init script [here](https://github.com/EndPointCorp/lg-live-image/commit/1ce4bc73e54546d6296e9753f6aac37304b95c23).  My work to include this in lg_persona is complete but hasn't been merged.

**Comment by axisofentropy** [comment]
Is this merged now?

**Comment by FuriousJulius** [comment]
The roscoe image changes and lg_persona stuff is all in place.  https://github.com/EndPointCorp/lg_ros_nodes/pull/151 needs to be merged into lg_ros_nodes and we should be good to go!

**Comment by FuriousJulius** [comment]
#151 was merged successfully.  Closing this issue
