### ISSUE TITLE
Fix tempdir (~/.googleearth/Cache|Temp) not being purged upon relaunch

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#155]
Here: https://github.com/EndPointCorp/lg_ros_nodes/blob/development/lg_earth/src/lg_earth/client.py#L120-L125

**Comment by wzin** [comment]
https://www.flowdock.com/app/endpoint/r-d/threads/LwPz-N08hhwP-MVZMqBH3TOewfg

It looks like we're setting the tempdir correctly but earth partially ignores that and puts some additional data to an uncontrolled, abovementioned dir.

**Comment by wzin** [comment]
#178 is a dup

**Comment by minshallj** [comment]
closing since when ros nodes update this will now happen via the soft relaunch
