### ISSUE TITLE
Fix viewsync broadcasting inside Docker

### ISSUE THREAD

**Issue by kiselev-dv** [EndPointCorp/lg_ros_nodes#160]
Only two out of three GE instances are synchronized. Closing one of the slaves restores synchronization for another slave GE.

Clue: it may be caused by UDP network stack implementation inside docker. Looks like only one UDP "subscriber" could recieve messages.

**Comment by kiselev-dv** [comment]
# Testing scenarion

- Build and run image. 
- Move master instance. 
- Check that both slaves changes camera  position.

**Comment by wzin** [comment]
related: #1277

**Comment by mvollrath** [comment]
Closing old issue.
