### ISSUE TITLE
Make it possible to relaunch to last state

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#168]
Save last USCS message on the filesystem between relaunches. related to #165

**Comment by axisofentropy** [comment]
Relaunches are often performed to return the system to a Known Good State.  So relaunches should probably unload everything they can.

Maybe there's a distinction to be made between different kinds of relaunches, but at least one option should forget everything.

**Comment by axisofentropy** [comment]
Relaunches are often performed to return the system to a Known Good State.  So relaunches should probably unload everything they can.

Maybe there's a distinction to be made between different kinds of relaunches, but at least one option should forget everything.
