### ISSUE TITLE
Investigate alternate approach for running applications

### ISSUE THREAD

**Issue by mvollrath** [EndPointCorp/lg_ros_nodes#17]
It's possible that we can use a different approach for launching, respawning, and tracking the desired state of applications.

* We can use any blocking call to keep a node alive.  This means we can use something as simple as `subprocess.call()` to run the process.  If the process dies, the node dies.  Roslaunch can handle respawning.

* Persistent global parameters can be used to track the desired state (think window visibility) of an application, allowing respawns to always return to that state.

What are the benefits?

* No more `Thread`-based process running.

* Leverage roslaunch respawn feature.

* Less moving parts and state managed in each node.

What are the risks?

* No more low-level process health checking routine.  We can implement a new blocking `ProcController` interface that runs a monitor thread to kill unresponsive processes.

* Node can't change parameters while respawning.  Any message changing the desired state must be accompanied by a parameter write.  This is complicated by the lack of parameter support in rosbridge.  This could be solved by running a separate node just to write the params, or by using latched topics (comes with its own dangers).

**Comment by minshallj** [comment]
I think this can be closed, agreed @mvollrath & @wzin ? Looks like `close_fds=True` was a good enough fix for this.

**Comment by wzin** [comment]
Yup - closing.
