### ISSUE TITLE
use rosunit instead of nosetests

### ISSUE THREAD

**Issue by zdenekmaxa** [EndPointCorp/lg_ros_nodes#195]
**Overview:**
nosetests runner misbehaves (ignores main section of the modules, ignores pytest directives - decorators, special methods). rosunit does the same job but behaves correcly.
ALL that is needed to is to replace nosetests command with rosunit in our tests_runner.py

opinions? @wzin @mvollrath @minshallj 

and since rosunit respects main section of the module, should the test module be written in the pytest style (like e.g. lg_stats tests), then we'll get nice failures reporting, nice pytest log output overall instead of chiefly suboptimal nosetests output

**Comment by wzin** [comment]
👍 for using anything but not nosetests. I remember many issues in Sept/Oct 2015 when you and @minshallj were working on tests.

**Comment by zdenekmaxa** [comment]
that's right. more over,  you know how much biased I am, but really, the more I have to do with various testing frameworks, the more I like and want to migrate everything to pytest. Alas, this is not possible with catkin, but rosunit seems it will do the same job plus the benefits I am listing.
as far as catkin CMakefile is concerned, it recognizes just add_rostest, catkin_add_nosetests but in our custom runner which we need to have, we can execute whatever we like. So I am suggesting nosetests -> rosunit in the runner script.

**Comment by mvollrath** [comment]
Why do we have a test_runner.py?  Catkin runs tests for us.  Here's the docs: http://docs.ros.org/indigo/api/catkin/html/howto/format2/index.html#configuring-and-running-unit-tests

**Comment by minshallj** [comment]
remember that it wasn't properly returning error values when there were errors in the scripts themselves. `test_runner.py` just looks through all the CMakeList.txt files and grabs out all tests and puts them into nosetest and rostest run lists and then calls them manually.

**Comment by zdenekmaxa** [comment]
@mvollrath it was so painful to rely fully on catkin tools. plus just as @minshallj said ...
