### ISSUE TITLE
Make dependencies message more verbose

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#196]
**Overview:**
Kmlsync is a good example. It depends on /kmlsync/state service. It should raise error after a timeout.

**Requirements:**
List of requirements that need to be satisfied that are needed to consider this feature implemented.
- make `depend_on_service` method more verbose
- raise error if service does not become available

**Comment by FuriousJulius** [comment]
Completed here: https://github.com/EndPointCorp/ros_cms/commit/ec98be9083340ae38f51308016fad0d604bd1d53
