### ISSUE TITLE
Smooth transitions and preloading

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#223]
Overview:

A typical javascript application that runs inside of an adhoc browser needs few seconds before it's loaded.

in other words: we have a 4 state state-machine - we introduce 5th intermediary state in between and want to have a callback for going from 3rd to 4th state

An asset loaded into a browser

We need to show a splash screen, progress bar or just create a hook for showing intermediary image before application is fully loaded and can be shown on the screen. This calls for a hook sent from application to the adhoc browser pool's browser instance (that js app runs in) for delayed ApplicationState.VISIBLE signal. Each javascript application would have to have know the unique ID of browser instance it's running inside of. In order to do this we'll need to append sth like ros_instance_id to get arguments of the browser so an extension or the application itself can send ApplicationSate.VISIBLE to the browser instance.

Design graph: https://drive.google.com/file/d/0B1VEo7XUZNtwd29lNGJfbXFRaE0/view?usp=sharing

Design Image:

![smooth transitions](https://cloud.githubusercontent.com/assets/353944/15575137/a23f8b7c-2351-11e6-92e1-a7d67ee2bfa6.png)

Scenario:
- launcher emits a message and subscribes to a channel on which it will wait for all groups to become ready - during waiting it presents specific waiting/loading behavior
- message contains information about 3 browsers belonging to two activity types (A and B) is published. Foo belongs to A, Baz and Bar belong to group B.
- all browsers from group B and A have preloaded but their content is not ready yet
- chrome extension inside Bar and Baz receved readiness signal and emitted a message about page load completion
- external ROS node noticed that all browsers from group B have joined and publishes a message informing browser pool that browsers belonging to group B can now become visible
- same as above happens for group B
- launcher turns it's state to `scene loaded` state

Scenario on the timeline:
https://www.draw.io/#G0B1VEo7XUZNtwZmVwOGZ2TGhyTlE
![smooth transitions logic](https://cloud.githubusercontent.com/assets/353944/17057252/2fd12a2e-5019-11e6-8dcf-c9bc96a91ed4.png)

**Comment by wzin** [comment]
@minshallj asked about prevent audio from being played back when the app is being preloaded in the background.

**Comment by wzin** [comment]
@mvollrath suggests using window API for chrome: https://developer.chrome.com/extensions/windows 
https://www.flowdock.com/app/endpoint/r-d/threads/QvbXcK2UoR1kNGwCg6RYVC8BSeP

**Comment by kiselev-dv** [comment]
We have some web applications which are not allows us to use custom get arguments, like google maps.

And we need some way to pass arguments from command line args from managed application into the chrome extension. As an Idea, we can use user agent string. It contains some sections, one of the sections is the section about host system. So we can add there some our stuff, like ros_node_name and such stuff. UA is easy accessible from js, and do not requires us to make a call for json data on the host.

**Comment by wzin** [comment]
@kiselev-dv another way to do that is to generate a static small html web page that would load first and redirect to google maps from it.
