### ISSUE TITLE
fix lg_stats issue on portal

### ISSUE THREAD

**Issue by zdenekmaxa** [EndPointCorp/lg_ros_nodes#239]
321581 ^[[0m^[[31m[ERROR] [WallTime: 1466692109.047650] bad callback: <bound method Processor.process of <lg_stats.meat.Processor object at 0x7efe087f7090>>
321582 Traceback (most recent call last):
321583   File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
321584     cb(msg)
321585   File "/opt/ros/indigo/lib/python2.7/dist-packages/lg_stats/meat.py", line 177, in process
321586     out_msg = self.get_outbound_message(msg)
321587   File "/opt/ros/indigo/lib/python2.7/dist-packages/lg_stats/meat.py", line 155, in get_outbound_message
321588     slot = self.get_slot(src_msg)  # this may raise EmptyIncomingMessage
321589   File "/opt/ros/indigo/lib/python2.7/dist-packages/lg_stats/meat.py", line 129, in get_slot
321590     slot = json.loads(getattr(msg, self.msg_slot))
321591   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
321592     return _default_decoder.decode(s)
321593   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
321594     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
321595 TypeError: expected string or buffer

needless to say that something like this is best caught / covered by an automatic test case.

**Comment by wzin** [comment]
could not find this exception on any of installations - lg_stats has been slightly refactored since this issue has been reported.

also - please don't wipe out the template and fill it in with all teh information that's required - debugging such issue having only a traceback is almost impossible.
