### ISSUE TITLE
Videos not working on EPHQLGXROS

### ISSUE THREAD

**Issue by BenWitten** [EndPointCorp/lg_ros_nodes#249]
**Overview:**
Very few videos are working on EPHQLGXROS, since the new rollout last week. A couple examples of this are **** Annual Report and MLB Playoff Matchup

**Comment by BenWitten** [comment]
This needs to be completed by end of day tomorrow at the latest.

**Comment by zdenekmaxa** [comment]
if some are working and some not, I would first suspect codecs rather than breakage in roscoe. as I have commented on relevant tickets, I have seen a bunch of videos from ephqlgxros not working at all while the mplayer functionality was flagged OK by @tj-endpoint

**Comment by wzin** [comment]
I've identified that it's browser video player that does not work properly.  Mplayer is fine.
