### ISSUE TITLE
lg_sv pov and panoid need to change simultaneously (fix sv/pv flickingering)

### ISSUE THREAD

**Issue by minshallj** [EndPointCorp/lg_ros_nodes#261]
**Overview:**
Director messages specify a POV for the new panoid. What ends up happening is either the POV or the panoid changes first. This leads to a bit of a flicker that can be quite odd looking.

**Requirements:**
List of requirements that need to be satisfied that are needed to consider this feature implemented.
- A new topic `/streetview/pano_and_pov` with a new message type that can hold all data needed
- A smooth transition between pano and pov all at once. Likely javascript side. Though the POV is constantly echoed by the server and could cause some issues

**Development notes**
Just that we need to somehow get the POV to be ignored by the server until it matches the new POV.

**Testing scenario**
Just change between a bunch of scenes that have streetview only.

**Comment by wzin** [comment]
#272 is related
