### ISSUE TITLE
Remove lg_cms_director from lg_ros_nodes

### ISSUE THREAD

**Issue by zdenekmaxa** [EndPointCorp/lg_ros_nodes#267]
**Overview:**
lg_cms_director ROS node has no tests, implement some.
The node's logic is all in the scripts, should be moved into src and tests covering that logic.

Two external libs are present in src - pulsar and trollius. both are availalbe on PYPI. It would probably be cleaner to remove them from our repo and package-use them.

**Requirements**:
- remove lg_cms_director from lg_ros_nodes
- remove lg_cms_director and DIRECTOR_URL from chef
- remove package from aptly scripts

**Comment by wzin** [comment]
This node is going to go away - not used anywhere - director now lives inside of the touchscreen. Renaming ticket.

**Comment by minshallj** [comment]
make sure to remove the package from `pack-debs`
