### ISSUE TITLE
Make a ROS node for emitting scenes for certain states

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#274]
**Overview:**

Now that we know how to emit messages informing us about certain states (active, inactive, online, offline, initial namely), we want a ros node to provide callback for these state changes (e.g from active -> inactive = on_inactive)

**Requirements:**
Make ros node that will emit appropriate messages (configurable via ROS params) for following states:
- active -> inactive (on_inactive)
- inactive -> active (on_active)
- offline -> online (on_online)
- online -> offline (on_offline)
- make it possible to parametrize urls for these scenes
- make these callbacks be enabled/disabled via configuration

**Development notes**

@minshallj's uscs node is a good place to gather all funcoinalities related to state emission

**Comment by zdenekmaxa** [comment]
- offline -> online (on_online)
- online -> offline (on_offline)

these messages are emitted by the lg_offliner ros node and are fully configurable:
https://github.com/EndPointCorp/lg_ros_nodes/blob/master/lg_offliner/test/online/test_lg_offliner_real.test#L13-L14
Certainly, it's possible to configure /director/scene messages as appropriate.
