### ISSUE TITLE
Mirror playback in browser instead of GStreamer

### ISSUE THREAD

**Issue by mvollrath** [EndPointCorp/lg_ros_nodes#283]
### Overview
We want to be able to overlay additional UI on the mirror playback window.  The current mirroring implementation uses GStreamer to play back the captured viewport stream, but this does not give us a good path to adding UI (since the elements we want to add are already being implemented with browser extensions).  It also does not have a path to supporting activity preload.

The quickest known way to satisfy this is to shortcut the TurboShark pipeline by sending the captured viewport stream to the gateway and bundling a simple webapp that plays back the stream while ignoring user input (overlay extension UI will still happily accept it).

### Requirements
* A webapp installed in the ROS stack for playing back mirroring streams.
* A mirror activity launches a browser pointing at that webapp instead of GStreamer.
* The playback browser loads any needed UI overlay extensions.

**Comment by mvollrath** [comment]
#284

**Comment by mvollrath** [comment]
Still needed: list of extensions to run on the playback browser.

**Comment by eggyknap** [comment]
If I have the right idea of what you're talking about, this exists in the
cms development branch
