### ISSUE TITLE
Spacenav doesn't keep an activity state active

### ISSUE THREAD

**Issue by peter-hank** [EndPointCorp/lg_ros_nodes#292]
**Overview:**
Using `spacenav` on `ephqlgxros` doesn't keep the system active and after a period of time `/activity/active` goes to false.

**Requirements:**
List of requirements that need to be satisfied that are needed to consider this feature implemented.
- spacenav should emit messages when using it to keep an activity state active

**Testing scenario**
- ssh to any system
- rostopic echo /activity/active
- relaunch the system
- ask someone to use the spacenav
- watch the /activity/active topic
- wait an activity timeout number of seconds
- /activity/active should be `True` and shouldn't change to `False` when using the specnav

**Comment by wzin** [comment]
Moved to backlog - needs to be fixed.
