### ISSUE TITLE
Kiosk mode support in adhoc browser mode

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#311]
**Overview:**

We need to be able to turn off kiosk mode

**Requirements:**
- Make `activity_config`: `google_chrome`: `kiosk`: `false` map to AdhocBrowser.msg's attribute `kiosk`: `false` - fall back to `true` by default

**Comment by wzin** [comment]
Deviation - 5->13

**Comment by minshallj** [comment]
Done and tested (I had to publish my own director message w/ `"kiosk": true` included since it's not supported yet in our cms) 6f773186c68f0e7abc4d8d5858d242fc603e38db
