### ISSUE TITLE
Point cloud viewer

### ISSUE THREAD

**Issue by eggyknap** [EndPointCorp/lg_ros_nodes#32]
We need a point cloud viewer one day, and now's probably a good time.

https://github.com/eggyknap/lg-potree-2 is a start, but needs a master service to track absolute position, handle director messages, and possibly send out other regular messages with the current point cloud, or other state stuff.

**Comment by wzin** [comment]
Closing - no motion.

**Comment by eggyknap** [comment]
Further discussion at https://www.flowdock.com/app/endpoint/r-d/threads/3zGxnx_UuZaeMYCXDrxbI86D94K

**Comment by mvollrath** [comment]
Closing old issue, hasn't been any demand and flowdock is gone.
