### ISSUE TITLE
Panoramic Video Player demo

### ISSUE THREAD

**Issue by mvollrath** [EndPointCorp/lg_ros_nodes#330]
A panoramic video player webapp has been tacked on to lg_sv for demonstration.

It lives at `lg_sv/webapps/panovideosync/` and has some options:

* `videoUrl`: required, url to the *equirectangular* panoramic video.  [compatibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats)
* `hFov`: horizontal FOV in degrees.
* `yawOffsets`: comma-separated list of yaw offsets in degrees.
* `master`: if true, this is the instance that acts as the clock master and plays audio.  Must have one master.

For SpaceNav, run an lg_sv `server.py` instance with `server_type` param set to `panovideo`.

To add scenes, make a `Web Page` asset for each display node and span all main displays with it and configure the video, fov and offsets.  The master should be whichever you want audio playing from.

For example, LGX 42-a Web Page asset would point at this url:

`http://localhost:8008/lg_sv/webapps/panovideosync/index.html?videoUrl=http://lg-head/nameofyour.mp4&master=true&hFov=29.75&yawOffsets=-30,0,30`

And 42-b:

`http://localhost:8008/lg_sv/webapps/panovideosync/index.html?videoUrl=http://lg-head/nameofyour.mp4&hFov=29.75&yawOffsets=-90,-60,60,90`

Upload videos to the head node `/var/www/`.  Note that [the server must support byte serving](http://superuser.com/questions/451445/how-can-i-test-if-a-server-supports-byte-serving/451447) and all head nodes do at this path.

**Comment by joshuanorman** [comment]
Unfortunately still unable to check on qatn with iso 2.2.0-rc11 -- webgl seems to broken

**Comment by wzin** [comment]
Closing - it's demoable.
