### ISSUE TITLE
Improve sync_to_displaynodes

### ISSUE THREAD

**Issue by FuriousJulius** [EndPointCorp/lg_ros_nodes#377]
**Overview:**
Lets give the `sync_to_displaynodes` script an option to update our checkouts (that are already on master) of the various repos in the systems `catkin/src/`.  This will help ensure you aren't testing outdated combinations of code.  Recently Dmitry went to test his cesium changes. The lg_cesium repo was on the branch he wanted to test, lg_ros_nodes repo was up to date but appctl was a single commit too old for everything to work.  Instead of having him manually fetch/pull each branch in his catkin/src lets do this automatically warning/ignoring if a repo is on something other than master.

**Requirements:**
-Safely pull the required repos
-Alert user if repo is out of date/on non standard branch
-Deploy latest to display node

**Comment by FuriousJulius** [comment]
finished here: https://github.com/EndPointCorp/lg_ros_nodes/commit/aac1113a7d9c92e99474152c6dc6daac4d7d996e

**Comment by minshallj** [comment]
possibly fixed. maybe @kiselev-dv could try it out? Just pull the latest from master

**Comment by wzin** [comment]
![big_1409275821_1382482410_image](https://user-images.githubusercontent.com/353944/31217334-f145ebc0-a9b6-11e7-8ffb-05a45254f924.jpg)
