### ISSUE TITLE
Global paths for common private params

### ISSUE THREAD

**Issue by mvollrath** [EndPointCorp/lg_ros_nodes#44]
Right now there's a lot of redundant configuration, for example:

```
<node name="earth_left_one" pkg="lg_earth" type="client" clear_params="true" respawn="true" respawn_delay="3">
  <param name="viewport" value="left_one"/>
  <param name="viewsync_recv" value="true"/>
  <param name="viewsync_hostname" value="10.42.42.255"/>
  <param name="horiz_fov" value="36"/>
  <param name="yaw_offset" value="36"/>
</node>
<node name="earth_center" pkg="lg_earth" type="client" clear_params="true" respawn="true" respawn_delay="3">
  <param name="viewport" value="center"/>
  <param name="viewsync_send" value="true"/>
  <param name="viewsync_hostname" value="10.42.42.255"/>
  <param name="spacenav_device" value="/dev/input/spacenavigator"/>
  <param name="horiz_fov" value="36"/>
</node>
```

We can factor out viewsync_hostname and horiz_fov (and some others).  For example, a global `/earth/horiz_fov` would serve as the default in absence of an explicit private `horiz_fov`.  This would be set in the head node's ros_params (a new feature of the lg_ros cookbook).

The logic for resolving these params:

```
if private parameter is set:
  use private parameter
elif global parameter is set:
  use global parameter
else:
  use baked-in default
```

This will help to reduce configuration bloat.

**Comment by minshallj** [comment]
I think this should do what we want, @mvollrath ?
http://wiki.ros.org/rospy_tutorials/Tutorials/Parameters#Searching_for_a_Parameter
```diff
diff --git a/lg_common/src/lg_common/helpers.py b/lg_common/src/lg_common/helpers.py
index af1f723..696aae8 100644
--- a/lg_common/src/lg_common/helpers.py
+++ b/lg_common/src/lg_common/helpers.py
@@ -482,3 +482,15 @@ def check_device(device, name):
     if not flag:
         os.chmod(device, original_mode)
     return flag
+
+
+def get_param(param_name, default):
+    """
+    Searches for parameter in the local scope, then moves
+    out to the global scope, if it's not found the default
+    is provided
+    """
+    param = rospy.search_param(param_name)
+    if param:
+        return rospy.get_param(param, default)
+    return default
```

**Comment by minshallj** [comment]
Doing rospy.search_param('~foo') results in an error, so there are a few paths we could go here:
1. we could just not pass the ~ to our own get_param search
2. we could strip off the ~, and just search for everything else
3. we could interpret any call with the ~ as a private param only search

**Comment by wzin** [comment]
@minshallj what about:

```python
rospy.get_param_names()
``` 

https://github.com/EndPointCorp/lg_chef/blob/43e0efab76ef7cde3ac69e9c51989aa75764425a/cookbooks/lg_ros/files/default/viewport_scene.py#L34

**Comment by mvollrath** [comment]
This is still relevant, but config overhaul needs to be more comprehensive.
