### ISSUE TITLE
Clean director dependencies:

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#51]
From matt's comments there are following options:

- Add some kind requirements.txt installing hook in every place that we are deploying (dev, ci, production iso). This makes the package dirty for open-source distribution, which I'm not sure we planned on anyway, but we need to prevent open-source packages from using requirements.txt because it's not kosher with ROS.
- Package the version of Pulsar we want for Ubuntu and add it to rosdep. We can host this dep and additional rosdep source lists locally/privately, too.
- Port from Pulsar to something else. I'm not aware of any specific technical requirement to use Pulsar, but this would not be a simple port.

**Comment by minshallj** [comment]
The director is dead now, right? @wzin

**Comment by wzin** [comment]
yup it's dead - it needs to stay there for compatibility for a while.
