### ISSUE TITLE
SV zoom support

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#99]
Child of https://github.com/EndPointCorp/lg_ros_nodes/issues/97

Requirements:
- pull/push of spacenav should make the pano zoom in and out 

Development notes:
- make support for translating spacenav data to vector of directions in separate node
- use the directions to zoom out / in
- zoom support should be parametrized

**Comment by minshallj** [comment]
This might not work as well as we want it to. There doesn't seem to be much support for fractional zooming in the streetview api.

https://groups.google.com/forum/#!topic/google-maps-js-api-v3/c7_ckUGKp7s

The zoom level / fov pairs look like this:
`(0, 127), (1, 90), (2, 53), (3, 28), (4, 14)`
When zoom levels aren't an even number, there is a small gap between the panos.

![img](https://cloud.githubusercontent.com/assets/2132951/10179267/b6f41614-66b9-11e5-8371-b601b68145db.png)

maybe @mvollrath can look into this. I'll be pushing my work into a branch, ft-sv_zoom
